-- DDL

CREATE TABLE TUSER (
	ID VARCHAR (50) PRIMARY KEY,
	EMAIL VARCHAR (255) UNIQUE NOT NULL,
	PASSWORD VARCHAR (50) NOT NULL,
	FIRST_NAME VARCHAR (50) NOT NULL,
	LAST_NAME VARCHAR (50) NOT NULL,
	PHONE_NUMBER VARCHAR (50) NOT NULL
);

-- DML
INSERT INTO TUSER (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('1', 'joao@gmail.com', 'Joao@123', 'Joao', 'Silva', '551199784512');
INSERT INTO TUSER (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('2', 'maria@gmail.com', 'Maria@123', 'Maria', 'Silva', '551199784511');
INSERT INTO TUSER (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('3', 'jose@gmail.com', 'Jose@123', 'Jose', 'Silva', '551199784513');
INSERT INTO TUSER (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('4', 'ana@gmail.com', 'Anaa@123', 'Ana', 'Silva', '551199784514');
INSERT INTO TUSER (ID, EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, PHONE_NUMBER) VALUES ('5', 'moises@gmail.com', 'Moises@123', 'Moises', 'Silva', '551199784515');